/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface PopUp {
    }
    interface ToggleButton {
        "mode": 'connected' | 'willLoad' | 'didLoad';
        "name": string;
    }
    interface ToggleGroup {
        "name": string;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPopUpElement extends Components.PopUp, HTMLStencilElement {
    }
    var HTMLPopUpElement: {
        prototype: HTMLPopUpElement;
        new (): HTMLPopUpElement;
    };
    interface HTMLToggleButtonElement extends Components.ToggleButton, HTMLStencilElement {
    }
    var HTMLToggleButtonElement: {
        prototype: HTMLToggleButtonElement;
        new (): HTMLToggleButtonElement;
    };
    interface HTMLToggleGroupElement extends Components.ToggleGroup, HTMLStencilElement {
    }
    var HTMLToggleGroupElement: {
        prototype: HTMLToggleGroupElement;
        new (): HTMLToggleGroupElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "pop-up": HTMLPopUpElement;
        "toggle-button": HTMLToggleButtonElement;
        "toggle-group": HTMLToggleGroupElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface PopUp {
    }
    interface ToggleButton {
        "mode"?: 'connected' | 'willLoad' | 'didLoad';
        "name": string;
    }
    interface ToggleGroup {
        "name": string;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "pop-up": PopUp;
        "toggle-button": ToggleButton;
        "toggle-group": ToggleGroup;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "pop-up": LocalJSX.PopUp & JSXBase.HTMLAttributes<HTMLPopUpElement>;
            "toggle-button": LocalJSX.ToggleButton & JSXBase.HTMLAttributes<HTMLToggleButtonElement>;
            "toggle-group": LocalJSX.ToggleGroup & JSXBase.HTMLAttributes<HTMLToggleGroupElement>;
        }
    }
}
